import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Button, Card, Input, Select } from "../../components/ui"; import { Mensagem } from "../../components/Mensagem";
import { api } from "../../services/api"; import { formatarCentavos, formatarData } from "../../utils/formatar"; import { getApiErrorMessage } from "../../utils/getApiErrorMessage";
type Versao={id:string;versao:number;vigenteDesde:string;precoPorBlocoCentavos:number;alunosPorBloco:number;blocosMinimosPorUnidade:number;moeda:string;_count:{assinaturas:number}};
type Plano={id:string;nome:string;descricao:string|null;ativo:boolean;produto:{codigo:string;nome:string};versoes:Versao[]};
export function Planos(){const[itens,setItens]=useState<Plano[]>([]),[produto,setProduto]=useState("sysbelt"),[erro,setErro]=useState(""),[planoId,setPlanoId]=useState(""),[preco,setPreco]=useState(""),[alunos,setAlunos]=useState("30");
 const carregar=useCallback(()=>api.get<{itens:Plano[]}>("/planos",{params:{produto,incluirHistorico:true}}).then(r=>setItens(r.data.itens)).catch(e=>setErro(getApiErrorMessage(e,"Não foi possível carregar os planos."))),[produto]);useEffect(()=>{void carregar()},[carregar]);
 async function publicar(e:FormEvent){e.preventDefault();try{await api.post(`/planos/${planoId}/versoes`,{vigenteDesde:new Date().toISOString(),alunosPorBloco:Number(alunos),precoPorBlocoCentavos:Math.round(Number(preco.replace(",","."))*100),blocosMinimosPorUnidade:1,moeda:"BRL",recursos:{}});setPlanoId("");await carregar()}catch(x){setErro(getApiErrorMessage(x,"Não foi possível publicar a versão."))}}
 async function status(p:Plano){await api.patch(`/planos/${p.id}/status`,{ativo:!p.ativo});await carregar()}
 return <><h1>Planos</h1><Select value={produto} onChange={e=>setProduto(e.target.value)}><option value="sysbelt">SysBelt</option><option value="mecanix">Mecanix</option><option value="psyche">Psyché</option></Select><Mensagem texto={erro}/>
 <div className="lista">{itens.map(p=><Card key={p.id}><div className="linha-titulo"><strong>{p.nome}</strong><Button onClick={()=>status(p)}>{p.ativo?"Desativar":"Ativar"}</Button></div>{p.versoes.map(v=><p key={v.id}>v{v.versao} · {formatarCentavos(v.precoPorBlocoCentavos)} · desde {formatarData(v.vigenteDesde)} · {v._count.assinaturas} assinatura(s)</p>)}</Card>)}</div>
 <Card><h2>Publicar nova versão</h2><form className="formulario" onSubmit={publicar}><label>Plano<Select required value={planoId} onChange={e=>setPlanoId(e.target.value)}><option value="">Escolha…</option>{itens.filter(p=>p.ativo).map(p=><option value={p.id} key={p.id}>{p.nome}</option>)}</Select></label><label>Preço (R$)<Input required value={preco} onChange={e=>setPreco(e.target.value)}/></label><label>Alunos por bloco<Input required type="number" value={alunos} onChange={e=>setAlunos(e.target.value)}/></label><Button type="submit">Publicar versão</Button></form></Card></>}
