import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Button, Card, Input, Select } from "../../components/ui"; import { Mensagem } from "../../components/Mensagem";
import { api } from "../../services/api"; import { formatarCentavos, formatarData } from "../../utils/formatar"; import { getApiErrorMessage } from "../../utils/getApiErrorMessage";
type Versao={id:string;versao:number;vigenteDesde:string;precoPorBlocoCentavos:number;alunosPorBloco:number;blocosMinimosPorUnidade:number;moeda:string;_count:{assinaturas:number}};
type Plano={id:string;nome:string;descricao:string|null;ativo:boolean;produto:{codigo:string;nome:string};versoes:Versao[]};
export function Planos(){const[itens,setItens]=useState<Plano[]>([]),[produto,setProduto]=useState("sysbelt"),[erro,setErro]=useState(""),[planoId,setPlanoId]=useState(""),[preco,setPreco]=useState(""),[alunos,setAlunos]=useState("30");
 const[nomeNovo,setNomeNovo]=useState(""),[descricaoNova,setDescricaoNova]=useState(""),[precoNovo,setPrecoNovo]=useState(""),[alunosNovo,setAlunosNovo]=useState("30"),[criando,setCriando]=useState(false);
 const carregar=useCallback(()=>api.get<{itens:Plano[]}>("/planos",{params:{produto,incluirHistorico:true}}).then(r=>setItens(r.data.itens)).catch(e=>setErro(getApiErrorMessage(e,"Não foi possível carregar os planos."))),[produto]);useEffect(()=>{void carregar()},[carregar]);
 async function criar(e:FormEvent){e.preventDefault();setCriando(true);setErro("");try{await api.post("/planos",{produtoCodigo:produto,nome:nomeNovo.trim(),descricao:descricaoNova.trim()||undefined,vigenteDesde:new Date().toISOString(),alunosPorBloco:Number(alunosNovo),precoPorBlocoCentavos:Math.round(Number(precoNovo.replace(",","."))*100),blocosMinimosPorUnidade:1,moeda:"BRL",recursos:{WHATSAPP:false,GATEWAY_AUTOMATICO:false,CONTROLE_ACESSO:false}});setNomeNovo("");setDescricaoNova("");setPrecoNovo("");setAlunosNovo("30");await carregar()}catch(x){setErro(getApiErrorMessage(x,"Não foi possível criar o plano."))}finally{setCriando(false)}}
 async function publicar(e:FormEvent){e.preventDefault();try{await api.post(`/planos/${planoId}/versoes`,{vigenteDesde:new Date().toISOString(),alunosPorBloco:Number(alunos),precoPorBlocoCentavos:Math.round(Number(preco.replace(",","."))*100),blocosMinimosPorUnidade:1,moeda:"BRL",recursos:{}});setPlanoId("");await carregar()}catch(x){setErro(getApiErrorMessage(x,"Não foi possível publicar a versão."))}}
 async function status(p:Plano){await api.patch(`/planos/${p.id}/status`,{ativo:!p.ativo});await carregar()}
 return <><h1>Planos</h1><Select value={produto} onChange={e=>setProduto(e.target.value)}><option value="sysbelt">SysBelt</option><option value="mecanix">Mecanix</option><option value="psyche">Psyché</option></Select><Mensagem texto={erro}/>
 <Card><h2>Criar plano com versão inicial</h2><form className="formulario" onSubmit={criar}><label>Nome<Input required minLength={2} value={nomeNovo} onChange={e=>setNomeNovo(e.target.value)}/></label><label>Descrição<Input value={descricaoNova} onChange={e=>setDescricaoNova(e.target.value)}/></label><label>Preço por bloco (R$)<Input required inputMode="decimal" value={precoNovo} onChange={e=>setPrecoNovo(e.target.value)}/></label><label>Alunos por bloco<Input required type="number" min={1} value={alunosNovo} onChange={e=>setAlunosNovo(e.target.value)}/></label><Button type="submit" disabled={criando}>{criando?"Criando…":"Criar plano"}</Button></form></Card>
 <div className="lista">{itens.map(p=><Card key={p.id}><div className="linha-titulo"><strong>{p.nome}</strong><Button onClick={()=>status(p)}>{p.ativo?"Desativar":"Ativar"}</Button></div>{p.versoes.map(v=><p key={v.id}>v{v.versao} · {formatarCentavos(v.precoPorBlocoCentavos)} · desde {formatarData(v.vigenteDesde)} · {v._count.assinaturas} assinatura(s)</p>)}</Card>)}</div>
 <Card><h2>Publicar nova versão</h2><form className="formulario" onSubmit={publicar}><label>Plano<Select required value={planoId} onChange={e=>setPlanoId(e.target.value)}><option value="">Escolha…</option>{itens.filter(p=>p.ativo).map(p=><option value={p.id} key={p.id}>{p.nome}</option>)}</Select></label><label>Preço (R$)<Input required value={preco} onChange={e=>setPreco(e.target.value)}/></label><label>Alunos por bloco<Input required type="number" value={alunos} onChange={e=>setAlunos(e.target.value)}/></label><Button type="submit">Publicar versão</Button></form></Card></>}
